swagger: '2.0'
info:
  version: v1
  title: aofguh
  description: adsfagas
host: 'localhost:2002'
basePath: /api
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /test430s/v1:
    get:
      tags:
        - Test430
      description: Gets all test430s from the system that the user has access to
      operationId: getTest430
      produces:
        - application/json
      x-swagger-router-controller: Test430
      responses:
        '200':
          description: test430 response
          schema:
            type: array
            items:
              $ref: '#/definitions/test430sv1'
        '404':
          description: test430 response
          schema:
            type: object
        '500':
          description: test430 response
          schema:
            type: object
      parameters:
        - name: pageSize
          in: query
          description: Number of records returned
          type: integer
        - name: pageNumber
          in: query
          description: Page number
          type: integer
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    post:
      tags:
        - Test430
      description: Posts all test430s from the system that the user has access to
      operationId: postTest430
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Test430
      responses:
        '200':
          description: test430 response
          schema:
            type: array
            items:
              $ref: '#/definitions/test430sv1'
        '404':
          description: test430 response
          schema:
            type: object
        '500':
          description: test430 response
          schema:
            type: object
      parameters:
        - name: test430s/v1
          in: body
          schema:
            $ref: '#/definitions/test430sv1'
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
  '/test430s/v1/{second attribute}':
    get:
      tags:
        - Test430
      description: Gets all test430s from the system that the user has access to
      operationId: getTest430Bysecond attribute
      produces:
        - application/json
      x-swagger-router-controller: Test430
      responses:
        '200':
          description: test430 response
          schema:
            type: object
            $ref: '#/definitions/test430sv1'
        '404':
          description: test430 response
          schema:
            type: object
        '500':
          description: test430 response
          schema:
            type: object
      parameters:
        - name: second attribute
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    put:
      tags:
        - Test430
      description: Puts all test430s from the system that the user has access to
      operationId: putTest430
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Test430
      responses:
        '200':
          description: test430 response
          schema:
            type: array
            items:
              $ref: '#/definitions/test430sv1'
        '404':
          description: test430 response
          schema:
            type: object
        '500':
          description: test430 response
          schema:
            type: object
      parameters:
        - name: test430s/v1
          in: body
          schema:
            $ref: '#/definitions/test430sv1'
        - name: second attribute
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    patch:
      tags:
        - Test430
      description: Patchs all test430s from the system that the user has access to
      operationId: patchTest430
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Test430
      responses:
        '200':
          description: test430 response
          schema:
            type: array
            items:
              $ref: '#/definitions/test430sv1'
        '404':
          description: test430 response
          schema:
            type: object
        '500':
          description: test430 response
          schema:
            type: object
      parameters:
        - name: test430s/v1
          in: body
          schema:
            $ref: '#/definitions/patchtest430sv1'
        - name: second attribute
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    delete:
      tags:
        - Test430
      description: Deletes all test430s from the system that the user has access to
      operationId: deleteTest430
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Test430
      responses:
        '204':
          description: test430 response
          schema:
            type: array
            items:
              $ref: '#/definitions/test430sv1'
        '404':
          description: test430 response
          schema:
            type: object
        '500':
          description: test430 response
          schema:
            type: object
      parameters:
        - name: second attribute
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  test430sv1:
    type: object
    properties:
      first attribute:
        type: array
        items:
          type: integer
          format: int32
      second attribute:
        type: string
        format: ''
    required:
      - first attribute
      - second attribute
  patchtest430sv1:
    type: object
    properties:
      first attribute:
        type: array
        items:
          type: integer
          format: int32
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
          tls-profile: ''
          secure-gateway: false
    catch: []
