swagger: '2.0'
info:
  version: v1
  title: asdf
  description: adf
  x-ibm-name: ''
host: $(catalog.host)
basePath: /api
schemes:
  - https
produces:
  - application/json
paths:
  /adfs/v1:
    get:
      tags:
        - Adf
      description: Gets all adfs from the system that the user has access to
      operationId: getAdf
      produces:
        - application/json
      x-swagger-router-controller: Adf
      responses:
        '200':
          description: adf response
          schema:
            type: array
            items:
              $ref: '#/definitions/adfsv1'
        '404':
          description: adf response
          schema:
            type: object
        '500':
          description: adf response
          schema:
            type: object
      parameters:
        - name: pageSize
          in: query
          description: Number of records returned
          type: integer
        - name: pageNumber
          in: query
          description: Page number
          type: integer
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    put:
      tags:
        - Adf
      description: Puts all adfs from the system that the user has access to
      operationId: putAdf
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Adf
      responses:
        '204':
          description: adf response
          schema:
            type: array
            items:
              $ref: '#/definitions/adfsv1'
        '404':
          description: adf response
          schema:
            type: object
        '500':
          description: adf response
          schema:
            type: object
      parameters:
        - name: adfs/v1
          in: body
          schema:
            $ref: '#/definitions/adfsv1'
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    post:
      tags:
        - Adf
      description: Posts all adfs from the system that the user has access to
      operationId: postAdf
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Adf
      responses:
        '204':
          description: adf response
          schema:
            type: array
            items:
              $ref: '#/definitions/adfsv1'
        '404':
          description: adf response
          schema:
            type: object
        '500':
          description: adf response
          schema:
            type: object
      parameters:
        - name: adfs/v1
          in: body
          schema:
            $ref: '#/definitions/adfsv1'
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    patch:
      tags:
        - Adf
      description: Patchs all adfs from the system that the user has access to
      operationId: patchAdf
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Adf
      responses:
        '204':
          description: adf response
          schema:
            type: array
            items:
              $ref: '#/definitions/adfsv1'
        '404':
          description: adf response
          schema:
            type: object
        '500':
          description: adf response
          schema:
            type: object
      parameters:
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    delete:
      tags:
        - Adf
      description: Deletes all adfs from the system that the user has access to
      operationId: deleteAdf
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Adf
      responses:
        '204':
          description: adf response
          schema:
            type: array
            items:
              $ref: '#/definitions/adfsv1'
        '404':
          description: adf response
          schema:
            type: object
        '500':
          description: adf response
          schema:
            type: object
      parameters:
        - name: adfs/v1
          in: body
          schema:
            $ref: '#/definitions/adfsv1'
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  adfsv1:
    type: object
    properties:
      adf:
        type: string
        format: ''
    required:
      - adf
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: 'https://.mybluemix.net$(request.path)$(request.search)'
          tls-profile: ''
          secure-gateway: false
    catch: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
